### ISSUE TITLE
Desenhar botão de "Chamar no WhatsApp"

### ISSUE THREAD

**Issue by kiratron** [emariacristina/emariacristina.github.io#8]
Estilizar link do "Chama no WhatsApp" como um botão e ao clicar enviar usuário para o WhatsApp da escola.

**Comment by kiratron** [comment]
Botão do WhatsApp implementado.
#11

**Comment by octalobo** [comment]
#11 Failed.

**Comment by octalobo** [comment]
#12 Merged.
